version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: mongo-container
    volumes:
      - mongo-data:/data/db
      - ./initdb:/docker-entrypoint-initdb.d
    ports:
      - "27017:27017"

  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - DATABASE_URL=mongodb://mongodb:27017/ecommerce
    depends_on:
      - mongodb

volumes:
  mongo-data:
