version: "3"

services:
  mongo-primary:
    image: mongo:latest
    hostname: mongo-primary
    container_name: mongo-primary-container
    command: mongod --replSet replset
    volumes:
      - mongo-primary-data:/data/db
      - ./etc/init:/docker-entrypoint-initdb.d:ro
    expose:
      - "27017"
    ports:
      - "27018:27017"
    restart: always

  mongo-secondary:
    image: mongo:latest
    hostname: mongo-secondary
    container_name: mongo-secondary-container
    command: mongod --replSet replset
    volumes:
      - mongo-secondary-data:/data/db
    expose:
      - "27017"
    restart: always

  mongo-arbiter:
    image: mongo:latest
    hostname: mongo-arbiter
    container_name: mongo-arbiter-container
    command: mongod --replSet replset
    expose:
      - "27017"
    restart: always

  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - DATABASE_URL=mongodb://mongo-primary:27017, mongo-secondary:27017, mongo-arbiter:27017/ecommerce?replicaSet=replset
    depends_on:
      - mongo-primary
      - mongo-secondary
      - mongo-arbiter

volumes:
  mongo-primary-data:
  mongo-secondary-data:
