name: バグ/エラー
description: 修正しなければいけないバグのIssue
labels: ['bug']
body:
  - type: markdown
    attributes:
      value: |
        バグ報告、および修正用のIssueテンプレートです。もしバグ以外のIssueを立てたい場合は、戻って再度Issueテンプレートを選択してください。どれにも当てはまらない場合は、テンプレートを使わずに作ることもできます。
  - type: textarea
    attributes:
      label: 再現手順
      description: どうやったらこのバグに遭遇するか書いてください。
      placeholder: |
        例:
        1. /xxx にアクセス
        2. Yが起こる
  - type: textarea
    attributes:
      label: 現在の挙動・予期される動作
      description: どういう挙動が起こっているか、どういう挙動が起こるべきか書いてください。
      placeholder: |
        例:
        - 現在の挙動: Yが起こる
        - 予期される動作: Zが起こるべき
  - type: dropdown
    attributes:
      label: 重要度
      options:
        - 'わからない'
        - '低 (積極的に修正しなくてもいい)'
        - '中 (修正したほうがいい)'
        - '高 (すぐに修正したほうがいい)'
      default: 0
  - type: textarea
    attributes:
      label: 他の情報
      description: |
        なにか他に情報があれば書いてください。例えば、バグが発生した環境や、バグを修正するために試したことなど。
      placeholder: |
        例:
        - バグを修正するために試したこと: npm install をやり直した