name: 機能追加/改善
description: 新しい機能を追加したり、既存の機能を改善するためのIssue
labels: ['enhancement']
body:
  - type: markdown
    attributes:
      value: |
        機能追加/改善のためのIssueテンプレートです。もしこれに当てはまらない場合は、戻って再度Issueテンプレートを選択してください。どれにも当てはまらない場合は、テンプレートを使わずに作ることもできます。
  - type: textarea
    attributes:
      label: 何を追加/改善したいか
      description: 何を追加/改善したいか書いてください。
      placeholder: |
        例:
        - 機能追加: /xxx にアクセスすると Y が起こる
        - 機能改善: /xxx にアクセスすると Y が起こるが、Z が起こるべき
    validations:
      required: true
  - type: dropdown
    attributes:
      label: 重要度
      options:
        - 'わからない'
        - '低 (積極的に取り掛からなくてもいい)'
        - '中 (取り掛かったほうがいい)'
        - '高 (すぐに取り掛かったほうがいい)'
    validations:
      required: true
  - type: textarea
    attributes:
      label: 他の情報
      description: |
        なにか他に情報があれば書いてください。例えば、実装方法など。
      placeholder: |
        例:
        - 実装方法: useXXX というフックを作成するべき
